// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace fwk.security.identity.core
{
    public partial class SecurityRulesInCategory
    {
        public Guid CategoryId { get; set; }
        public Guid RuleId { get; set; }

        public virtual SecurityRulesCategory Category { get; set; }
        public virtual SecurityRules Rule { get; set; }
    }
}