// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace fwk.security.identity.core
{
    public partial class SecurityRolesInRules
    {
        public Guid RolId { get; set; }
        public Guid RuleId { get; set; }

        public virtual SecurityRoles Rol { get; set; }
        public virtual SecurityRules Rule { get; set; }
    }
}