// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace fwk.security.identity.core
{
    public partial class SecurityRulesCategory
    {
        public SecurityRulesCategory()
        {
            SecurityRulesInCategory = new HashSet<SecurityRulesInCategory>();
        }

        public Guid CategoryId { get; set; }
        public string Name { get; set; }
        public Guid? ParentCategoryId { get; set; }
        public Guid? InstitutionId { get; set; }
        public virtual ICollection<SecurityRulesInCategory> SecurityRulesInCategory { get; set; }
    }
}