// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace fwk.security.identity.core
{
    public partial class SecurityRules
    {
        public SecurityRules()
        {
            SecurityRolesInRules = new HashSet<SecurityRolesInRules>();
            SecurityRulesInCategory = new HashSet<SecurityRulesInCategory>();
        }

        public Guid Id { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }

       // public Guid? InstitutionId { get; set; }
        public virtual ICollection<SecurityRolesInRules> SecurityRolesInRules { get; set; }
        public virtual ICollection<SecurityRulesInCategory> SecurityRulesInCategory { get; set; }
    }
}